apiVersion: apps/v1
kind: Deployment
metadata: 
  name: book-store-deployment
  namespace: default
  labels:
    app: books-store
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      containers:
      - name: book-store
        image: gcr.io/sodium-dynamo-292520/book-store
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 80m
          limits:
            cpu: 100m
