apiVersion: v1
kind: Service
metadata: 
  name: book-store-internal-service
  namespace: default
spec:
  selector:
    app: book-store
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
